### ISSUE TITLE
thank you

### ISSUE THREAD

**Issue by gene-git** [rda0/web-greeter-theme-luminosity#1]
Great theme - and I see you fixed the background image problem i was staring at!

**Comment by gene-git** [comment]
Testing your background updates. Now I see thumbnails for foo.jpg files, but not for foo.png, They still work as background just missing thumbnail.
Not right - there are thumbnails for images in the luminosity/img/wallpapers but not for images in the branding.background_images_dir - but selecting them works as background - just no thumbnails regardless if jpg or png.

**Comment by rda0** [comment]
You can run `/usr/share/web-greeter/themes/luminosity/generate-images.py` which generates the thumbnails. But it is currently hardcoded to only look in `/usr/share/backgrounds`.

**Comment by gene-git** [comment]
Thanks will take a look

**Comment by rda0** [comment]
I should probably update the script to get `branding.background_images_dir` from `web-greeter.yml`

**Comment by gene-git** [comment]
That would be good - nicer than adding dirs on command line which was my plan :)

**Comment by rda0** [comment]
The correct path should now be picked up from the config

**Comment by gene-git** [comment]
That was fast - excellent - thank you
